"""
   inputs_gizmo_carver.py

   Purpose:
        Input file for RadMC carving routines. This is the only file you should
        edit. Follow the comments below to see what each variable represents.

   Author:
        Sean Feng, feng.sean01@utexas.edu
        Spring 2022
        
        Modified from:
        inputs_CarveOut.py, written by
        Aaron T. Lee, aaron.t.lee@utexas.edu
        Spring 2018

   Written/Tested with Python 3.9, yt 4.0.2
"""

from yt.units import * 

# Constants for calculating derived fields
dust_to_gas = 0.01
hydrogen_ratio = 2.33
microturbulence_speed = 1000 # cgs
gamma = 5.0/3.0 # Note gamma is not constant and this function is an approximation.
helium_mass_fraction = 0.24 # Default mass fraction in Gizmo

# number fraction of target species
molecular_abundance = 10**-7 # abundance of NH3

# Units of the below box values ('pc','cm','AU','ly' accepted)
box_units = 'pc'

# x, y, z coordinates for the center of the carved domain (e.g., location of a star core)
# The values should match the unit given by box_units
box_center = [15.95957649, 15.54566532, 15.19446488]

# Routine will generate input files for a square area centered at box_center 
# extending to box_center += box_size on each side
# Use same units as box_units
box_size = 0.1 # pc

# Resolution of the resulting image (give as a complex number, e.g. for 
# box_dim = 64j, the resulting image will be 64x64)
box_dim = 64j

# Filepath of the HDF5 file name to read in
# If the HDF5 file is located in the same directory as the script files, 
# you can just put the file name
hdf5_file = '..\M2e3_mid.hdf5'

# unit base to use for calculations
unit_base = {'UnitMagneticField_in_gauss':  1e+4,
             'UnitLength_in_cm'         : 3.08568e+18,
             'UnitMass_in_g'            :   1.989e+33,
             'UnitVelocity_in_cm_per_s' :      100}

# Filepath for directory containing input files that are not generated by the carver routine.
# These files are still necessary for running RADMC-3D. The files are:
# camera_wavelength_micron.inp
# dustkappa_silicate.inp
# dustopac.inp
# lines.inp
# molecule_nh3.inp (Or data file for other target species)
# radmc3d.inp
# wavelength_micron.inp
existing_filepath = '..\default_files'

# Filepath for storing output files. Routine will make a working directory within this
# output directory for each run.
output_filepath = '..\output_files'

# Output file names for use in RADMC3D
out_afname = "amr_grid.inp"       # output file name for amr grid
out_nfname = "numberdens_nh3.inp" # output file name for target species above
out_vfname = "gas_velocity.inp"   # output file name for velocity
out_tfname = "gas_temperature.inp"    # output file name for temperature
out_ddfname = "dust_density.inp" # output file name for dust density
out_dtfname = "dust_temperature.dat" # output for dust temperature (requires .dat)
out_mtfname = "microturbulence.inp" # output for microturbulence

# Names of existing files
out_molname = 'molecule_nh3.inp' # (Or data file for other target species)
out_wlmname = 'wavelength_micron.inp'
out_cwlname = 'camera_wavelength_micron.inp'
out_dksname = 'dustkappa_silicate.inp'
out_dtpname = 'dustopac.inp'
out_linname = 'lines.inp'
out_rmcname = 'radmc3d.inp'